In [2]:
from juliacall import Main as jl
import numpy as np

[juliapkg] Locating Julia ^1.6.1
[juliapkg] Using Julia 1.10.0 at /home/user1/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/bin/julia
[juliapkg] Using Julia project at /home/user1/.miniconda3/envs/202401tfjax/julia_env
[juliapkg] Installing packages:
           julia> import Pkg
           julia> Pkg.add([Pkg.PackageSpec(name="PythonCall", uuid="6099a3de-0909-46bc-b1f4-468b9a2dfc0d")])
           julia> Pkg.resolve()
           julia> Pkg.precompile()


    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
   Installed MicroMamba ───── v0.1.14
   Installed JSON3 ────────── v1.14.0
   Installed micromamba_jll ─ v1.4.9+0
   Installed UnsafePointers ─ v1.0.0
   Installed CondaPkg ─────── v0.2.22
   Installed Pidfile ──────── v1.3.0
   Installed StructTypes ──── v1.10.0
   Installed PythonCall ───── v0.9.15
    Updating `~/.miniconda3/envs/202401tfjax/julia_env/Project.toml`
  [6099a3de] + PythonCall v0.9.15
    Updating `~/.miniconda3/envs/202401tfjax/julia_env/Manifest.toml`
  [992eb4ea] + CondaPkg v0.2.22
  [9a962f9c] + DataAPI v1.16.0
  [e2d170a0] + DataValueInterfaces v1.0.0
  [82899510] + IteratorInterfaceExtensions v1.0.0
  [692b3bcd] + JLLWrappers v1.5.0
  [0f8b85d8] + JSON3 v1.14.0
  [1914dd2f] + MacroTools v0.5.13
  [0b3b1443] + MicroMamba v0.1.14
  [bac558e1] + OrderedCollections v1.6.3
  [69de0a69] + Parsers v2.8.1
  [fa939f87] + Pidfile v1.3.0
  [aea7be01] + PrecompileTools v1.2.0
  [212

In [3]:
jl.pwd()

'/home/user1/Dropbox/code/vorpy'

In [4]:
jl.Pkg.activate('.')

  Activating project at `~/Dropbox/code/vorpy`


In [5]:
jl.Pkg.status()

Status `~/Dropbox/code/vorpy/Project.toml`
  [6e4b80f9] BenchmarkTools v1.4.0
  [052768ef] CUDA v5.2.0
⌃ [de52edbc] Integrals v4.1.0
⌃ [91a5bcdd] Plots v1.39.0
  [90137ffa] StaticArrays v1.9.2
Info Packages marked with ⌃ have new versions available and may be upgradable.


In [6]:
# jl.include('julia_src/biot_savart.jl')  # CPU version
jl.include('julia_src/biot_savart_cuda.jl')  # GPU version

weighted_biot_savart_kernel (generic function with 1 method)

In [7]:
# Set up vortex and field points
vp = np.array([[-1000, 0. , 0], [1000, 0 , 0]])
vc = 0.1 * np.ones(2)
y = np.arange(0, 20, 2, dtype=np.float64)  # np.linspace(0, 20, 10)
y[0] = 1e-3
fp = np.zeros((10, 3))
fp[:, 1] = y
print('vp =\n', vp)
print('vc =\n', vc)
print('y =\n', y)
print('fp.shape =', fp.shape)

vp =
 [[-1000.     0.     0.]
 [ 1000.     0.     0.]]
vc =
 [0.1 0.1]
y =
 [1.0e-03 2.0e+00 4.0e+00 6.0e+00 8.0e+00 1.0e+01 1.2e+01 1.4e+01 1.6e+01
 1.8e+01]
fp.shape = (10, 3)


In [104]:
vel = np.zeros(fp.shape[0])
for i in range(fp.shape[0]):
    vel[i] = jl.weighted_biot_savart_kernel(fp[i], vp.T, vc, lambda x: 1.0, jl.uniform_trapezoidal_rule)[1]



TypeError: 'float' object is not iterable

In [92]:
print('vel =\n', vel)

vel =
 [2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000.]
