In [1]:
from juliacall import Main as jl
import numpy as np

In [2]:
jl.pwd()

'/Users/morty/Library/CloudStorage/Dropbox/code/vorpy'

In [3]:
jl.Pkg.activate('.')

  Activating project at `~/Library/CloudStorage/Dropbox/code/vorpy`


In [4]:
jl.Pkg.status()

Status `~/Library/CloudStorage/Dropbox/code/vorpy/Project.toml`
  [de52edbc] Integrals v4.1.0
  [91a5bcdd] Plots v1.39.0


In [102]:
jl.include('julia_src/biot_savart.jl')

Error: 4.440892098500626e-16


weighted_biot_savart_kernel (generic function with 1 method)

In [103]:
# Set up vortex and field points
vp = np.array([[-1000, 0. , 0], [1000, 0 , 0]])
vc = 0.1 * np.ones(2)
y = np.arange(0, 20, 2, dtype=np.float64)  # np.linspace(0, 20, 10)
y[0] = 1e-3
fp = np.zeros((10, 3))
fp[:, 1] = y
print('vp =\n', vp)
print('vc =\n', vc)
print('y =\n', y)
print('fp.shape =', fp.shape)

vp =
 [[-1000.     0.     0.]
 [ 1000.     0.     0.]]
vc =
 [0.1 0.1]
y =
 [1.0e-03 2.0e+00 4.0e+00 6.0e+00 8.0e+00 1.0e+01 1.2e+01 1.4e+01 1.6e+01
 1.8e+01]
fp.shape = (10, 3)


In [104]:
vel = np.zeros(fp.shape[0])
for i in range(fp.shape[0]):
    vel[i] = jl.weighted_biot_savart_kernel(fp[i], vp.T, vc, lambda x: 1.0, jl.uniform_trapezoidal_rule)[1]



TypeError: 'float' object is not iterable

In [92]:
print('vel =\n', vel)

vel =
 [2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000.]
